### PR TITLE
chore: update to build with rust 1.80

### PR DESCRIPTION
**Pull request by chenrui333**
seeing some time related failure 

```
error[E0282]: type annotations needed
  --> src/main.rs:27:44
   |
27 |     let args: Box<_> = env::args().skip(1).collect();
   |                                            ^^^^^^^ cannot infer type of the type parameter `B` declared on the method `collect`
28 |     for arg in args.iter() {
   |                     ---- type must be known at this point
   |
help: consider specifying the generic argument
   |
27 |     let args: Box<_> = env::args().skip(1).collect::<Vec<_>>();
   |                                                   ++++++++++
 
For more information about this error, try `rustc --explain E0282`.
```

relates to https://github.com/Homebrew/homebrew-core/pull/178436

### CODE REVIEW

**Comment by kyontan** [comment]
Thanks for the PR!

For whom need the pre-built binary, I forked this repo and released to GitHub.
https://github.com/kyontan/fcp/releases/tag/v0.3.0

**Comment by Svetlitski** [comment]
Superseded by #46
